"""
Canonical BFF action catalog (BFF-FINAL-004).

This module is the single source of truth for all operator-facing actions.
The frontend maps these descriptors into ActionDescriptor[] and never invents
action truth on its own.

Each entry expresses:
  - action_id       : matches CommandType value
  - entity_type     : the ObjectType the action targets
  - endpoint        : canonical BFF endpoint for command submission
  - risk_level      : low | medium | high | critical
  - requires_*      : approval / confirm_token / two_man gates
  - cooldown_seconds: minimum re-trigger interval
  - idempotency_required: whether Idempotency-Key is mandatory
  - required_roles  : minimum RBAC role set
  - description     : human-readable action summary
"""
from __future__ import annotations

from models import BffActionCatalogEntry, BffActionCatalogResponse, RiskLevel

_FINAL_COMMAND_ENDPOINT = "/bff/v1/commands"

_CATALOG_ENTRIES: list[BffActionCatalogEntry] = [
    # ------------------------------------------------------------------ #
    # Approval / decision governance
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="ApproveDeployment",
        entity_type="DeploymentPlan",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=True,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Approve a pending deployment plan for execution.",
    ),
    BffActionCatalogEntry(
        action_id="ApproveDecision",
        entity_type="ApprovalDecision",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=True,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Approve a pending governance decision.",
    ),
    BffActionCatalogEntry(
        action_id="RejectDecision",
        entity_type="ApprovalDecision",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Reject a pending governance decision.",
    ),
    BffActionCatalogEntry(
        action_id="RequestApprovalRevision",
        entity_type="ApprovalDecision",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver", "operator"],
        description="Request a revision to a pending approval before it can be accepted.",
    ),
    # ------------------------------------------------------------------ #
    # Runtime control
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="StartRuntime",
        entity_type="Runtime",
        endpoint="/bff/runtimes/{runtime_id}/actions/StartRuntime",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=True,
        requires_two_man=True,
        cooldown_seconds=60,
        idempotency_required=True,
        required_roles=["runtime_operator", "live_owner_approver"],
        description="Start a stopped runtime binding; two-man authorization required for live runtimes.",
    ),
    BffActionCatalogEntry(
        action_id="RestartPaperRuntime",
        entity_type="Runtime",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=90,
        idempotency_required=True,
        required_roles=["operator", "runtime_operator"],
        description=(
            "Restart a paper runtime worker through the protected runtime-manager "
            "repair path; success is heartbeat freshness, not trade count."
        ),
    ),
    BffActionCatalogEntry(
        action_id="RestartTelemetryBridge",
        entity_type="Runtime",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=90,
        idempotency_required=True,
        required_roles=["operator", "runtime_operator"],
        description=(
            "Restart the telemetry bridge for a paper runtime through the protected "
            "runtime-manager repair path; no broker or capital authority is granted."
        ),
    ),
    BffActionCatalogEntry(
        action_id="TerminateStalePaperMonitoringSession",
        entity_type="Runtime",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=90,
        idempotency_required=True,
        required_roles=["operator", "runtime_operator"],
        description=(
            "Terminate a paper monitoring session only when stale heartbeat evidence "
            "is supplied; no session is ended from status alone."
        ),
    ),
    BffActionCatalogEntry(
        action_id="StartPaperMonitoringSession",
        entity_type="Runtime",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=90,
        idempotency_required=True,
        required_roles=["operator", "runtime_operator"],
        description=(
            "Start a paper monitoring session through runtime-manager after repair "
            "preconditions pass; success is fresh monitoring heartbeat."
        ),
    ),
    BffActionCatalogEntry(
        action_id="ProbeTelemetryIngest",
        entity_type="Runtime",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "runtime_operator"],
        description=(
            "Probe telemetry ingest freshness through a governed runtime repair "
            "command; the action is read-only and emits an audit receipt."
        ),
    ),
    BffActionCatalogEntry(
        action_id="PauseRuntime",
        entity_type="Runtime",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Pause a live runtime binding; no new orders will be placed.",
    ),
    BffActionCatalogEntry(
        action_id="PauseExecution",
        entity_type="Runtime",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=10,
        idempotency_required=True,
        required_roles=["operator"],
        description="Pause execution within a runtime without full binding suspension.",
    ),
    BffActionCatalogEntry(
        action_id="IssueRiskOff",
        entity_type="Runtime",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=60,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Issue a risk-off signal to halt new risk-taking positions.",
    ),
    BffActionCatalogEntry(
        action_id="IssueSafeMode",
        entity_type="Runtime",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=60,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Switch a runtime into safe mode; reduces exposure and disables new strategies.",
    ),
    BffActionCatalogEntry(
        action_id="AlertAcknowledge",
        entity_type="RiskAlert",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator"],
        description="Acknowledge a risk alert without mutating runtime or capital state.",
    ),
    # ------------------------------------------------------------------ #
    # Rollback lifecycle
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="ExecuteRollback",
        entity_type="Rollback",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=True,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=120,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Execute a previously prepared rollback plan.",
    ),
    BffActionCatalogEntry(
        action_id="ApproveRollback",
        entity_type="Rollback",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Approve a pending rollback plan so it can be executed.",
    ),
    BffActionCatalogEntry(
        action_id="RejectRollback",
        entity_type="Rollback",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Reject a pending rollback plan and cancel the rollback flow.",
    ),
    BffActionCatalogEntry(
        action_id="HardRollback",
        entity_type="Rollback",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.CRITICAL,
        requires_approval=True,
        requires_confirm_token=True,
        requires_two_man=True,
        cooldown_seconds=300,
        idempotency_required=True,
        required_roles=["approver"],
        description="Force an immediate hard rollback with full capital unwind; requires two-man authorization.",
    ),
    # ------------------------------------------------------------------ #
    # Kill switch
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="ActivateKillSwitch",
        entity_type="KillSwitchOrder",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.CRITICAL,
        requires_approval=True,
        requires_confirm_token=True,
        requires_two_man=True,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Activate the system-wide kill switch; halts all trading and unwinds positions.",
    ),
    # ------------------------------------------------------------------ #
    # Capital pool operations
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="ApprovePool",
        entity_type="CapitalPool",
        endpoint="/bff/capital-pools/{pool_id}/actions/ApprovePool",
        risk_level=RiskLevel.HIGH,
        requires_approval=True,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["treasury_approver"],
        description="Approve a capital pool draft; transitions state from draft to approved (one-way).",
    ),
    BffActionCatalogEntry(
        action_id="LiquidateAll",
        entity_type="CapitalPool",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.CRITICAL,
        requires_approval=True,
        requires_confirm_token=True,
        requires_two_man=True,
        cooldown_seconds=300,
        idempotency_required=True,
        required_roles=["approver"],
        description="Liquidate all positions in a capital pool; requires two-man authorization.",
    ),
    # ------------------------------------------------------------------ #
    # Evolution / diff governance
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="EscalateDiff",
        entity_type="EvolutionDecision",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator"],
        description="Escalate a strategy diff for human governance review.",
    ),
    BffActionCatalogEntry(
        action_id="ApproveEvolutionDecision",
        entity_type="EvolutionDecision",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=True,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Approve an evolution decision to allow strategy parameter changes.",
    ),
    BffActionCatalogEntry(
        action_id="ExecuteEvolutionAction",
        entity_type="EvolutionDecision",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=True,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=60,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Execute a previously approved evolution action.",
    ),
    # ------------------------------------------------------------------ #
    # Mutation review
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="ApproveMutation",
        entity_type="ApprovalDecision",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=True,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Approve a pending mutation decision.",
    ),
    BffActionCatalogEntry(
        action_id="RejectMutation",
        entity_type="ApprovalDecision",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Reject a pending mutation decision.",
    ),
    BffActionCatalogEntry(
        action_id="ReviewMutation",
        entity_type="ApprovalDecision",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.LOW,
        requires_approval=True,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["reviewer", "approver"],
        description="Mark a proposed mutation decision as reviewed.",
    ),
    BffActionCatalogEntry(
        action_id="ExecuteMutation",
        entity_type="ApprovalDecision",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=True,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=60,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Execute a previously approved mutation decision.",
    ),
    # ------------------------------------------------------------------ #
    # Sponsor / committee governance
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="RecordSponsorDecision",
        entity_type="CommitteeBoard",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Record a committee sponsor decision (approved / rejected / conditional).",
    ),
    # ------------------------------------------------------------------ #
    # HIQ Sentinel interventions (v5)
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="RemediateSentinelIntervention",
        entity_type="SentinelIntervention",
        endpoint="/bff/v5/interventions/{intervention_id}/remediate",
        risk_level=RiskLevel.CRITICAL,
        requires_approval=True,
        requires_confirm_token=True,
        requires_two_man=True,
        cooldown_seconds=60,
        idempotency_required=True,
        required_roles=["approver"],
        description="Execute HIQ Sentinel remediation for a pending intervention; requires two-man authorization.",
    ),
    # ------------------------------------------------------------------ #
    # HumanGate and PM-12 governance advisory write admission (BFF-B5-001)
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="HumanGateApprove",
        entity_type="HumanGateItem",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=True,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Approve a HumanGate item from the Management human inbox; high-risk items require two-man authorization.",
    ),
    BffActionCatalogEntry(
        action_id="HumanGateReject",
        entity_type="HumanGateItem",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=True,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Reject a HumanGate item from the Management human inbox; high-risk items require two-man authorization.",
    ),
    BffActionCatalogEntry(
        action_id="HumanGateRequestMoreEvidence",
        entity_type="HumanGateItem",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "reviewer", "approver"],
        description="Request more evidence for a HumanGate item before approval or rejection.",
    ),
    BffActionCatalogEntry(
        action_id="HumanGateRevoke",
        entity_type="HumanGateItem",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=True,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Revoke a previously admitted HumanGate decision fail-closed; high-risk items require two-man authorization.",
    ),
    BffActionCatalogEntry(
        action_id="HumanGateExtendTtl",
        entity_type="HumanGateItem",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["approver"],
        description="Extend the TTL for a pending HumanGate item through command admission.",
    ),
    BffActionCatalogEntry(
        action_id="QuarterlyRankingRecommendationSubmit",
        entity_type="Ranking",
        endpoint=_FINAL_COMMAND_ENDPOINT,
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Submit a PM-12 quarterly ranking recommendation into governance without direct live capital mutation.",
    ),
    # ------------------------------------------------------------------ #
    # Strategy / persona resource actions (BFF-LUV-GAP-002)
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="StrategyAction",
        entity_type="Strategy",
        endpoint="/bff/strategies/{strategy_id}/actions/{action_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic strategy lifecycle action (edit, submit, retire, dry-run wiring); precondition gates flow through the action catalog and command queue.",
    ),
    BffActionCatalogEntry(
        action_id="PersonaAction",
        entity_type="Persona",
        endpoint="/bff/personas/{persona_id}/actions/{action_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic persona lifecycle action (edit, retire, route-policy update, test-prompt wiring); precondition gates flow through the action catalog and command queue.",
    ),
    # ------------------------------------------------------------------ #
    # Capital / ranking / rebalance resource actions (BFF-LUV-GAP-003)
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="CapitalPoolAction",
        entity_type="CapitalPool",
        endpoint="/bff/capital-pools/{pool_id}/actions/{action_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic capital pool lifecycle action (activate, freeze, retire, allocation update); precondition gates flow through the action catalog and command queue.",
    ),
    BffActionCatalogEntry(
        action_id="RankingFormulaAction",
        entity_type="RankingFormula",
        endpoint="/bff/ranking/formulas/{formula_id}/actions/{action_id}",
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic ranking formula lifecycle action (activate, deactivate, recompute); precondition gates flow through the action catalog and command queue.",
    ),
    BffActionCatalogEntry(
        action_id="RebalanceAction",
        entity_type="Rebalance",
        endpoint="/bff/rebalances/{rebalance_id}/actions/{action_id}",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic rebalance lifecycle action (approve, cancel, reconcile); risky and routes through the command/precondition machinery.",
    ),
    BffActionCatalogEntry(
        action_id="RankingAction",
        entity_type="Ranking",
        endpoint="/bff/rankings/{ranking_id}/actions/{action_id}",
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic ranking lifecycle action (refresh, archive, tag); precondition gates flow through the action catalog and command queue.",
    ),
    # ------------------------------------------------------------------ #
    # Tools / MCP servers / skills resource actions (BFF-LUV-GAP-008)
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="ToolAction",
        entity_type="Tool",
        endpoint="/bff/tools/{tool_id}/actions/{action_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic tool lifecycle action (enable, disable, configure); precondition gates flow through the action catalog and command queue.",
    ),
    BffActionCatalogEntry(
        action_id="McpServerAction",
        entity_type="McpServer",
        endpoint="/bff/mcp/servers/{server_id}/actions/{action_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic MCP server lifecycle action (connect, disconnect, refresh); precondition gates flow through the action catalog and command queue.",
    ),
    BffActionCatalogEntry(
        action_id="SkillAction",
        entity_type="Skill",
        endpoint="/bff/skills/{skill_id}/actions/{action_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic skill lifecycle action (enable, disable, configure, promote); precondition gates flow through the action catalog and command queue.",
    ),
    # ------------------------------------------------------------------ #
    # Governance / runtime / risk / incident actions (BFF-LUV-GAP-005)
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="ReviewAction",
        entity_type="Review",
        endpoint="/bff/reviews/{review_id}/actions/{action_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic governance review action (approve, reject, escalate, request changes); routes through command admission and audit metadata.",
    ),
    BffActionCatalogEntry(
        action_id="DeploymentAction",
        entity_type="Deployment",
        endpoint="/bff/deployments/{deployment_id}/actions/{action_id}",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic deployment lifecycle action exposed for execute-plans compatibility; command admission returns the final envelope.",
    ),
    BffActionCatalogEntry(
        action_id="RuntimeAction",
        entity_type="RuntimeBinding",
        endpoint="/bff/runtimes/{runtime_id}/actions/{action_id}",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic runtime lifecycle action (pause, resume, risk-off preparation); command admission returns the final envelope.",
    ),
    BffActionCatalogEntry(
        action_id="RiskAlertAction",
        entity_type="RiskAlert",
        endpoint="/bff/risk/alerts/{alert_id}/actions/{action_id}",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic risk alert action (acknowledge, escalate, suppress); command admission returns the final envelope.",
    ),
    BffActionCatalogEntry(
        action_id="IncidentAction",
        entity_type="Incident",
        endpoint="/bff/incidents/{incident_id}/actions/{action_id}",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Generic incident lifecycle action (assign, escalate, resolve); command admission returns the final envelope.",
    ),
    BffActionCatalogEntry(
        action_id="EvolutionProgramAction",
        entity_type="EvolutionProgram",
        endpoint="/bff/evolution-programs/{program_id}/actions/{action_id}",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=60,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Evolution program lifecycle action (pause, resume, archive); command admission returns the final envelope.",
    ),
    BffActionCatalogEntry(
        action_id="ExperimentAction",
        entity_type="Experiment",
        endpoint="/bff/experiments/{experiment_id}/actions/{action_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Experiment lifecycle action (cancel, promote, archive); command admission returns the final envelope.",
    ),
    BffActionCatalogEntry(
        action_id="JobAction",
        entity_type="Job",
        endpoint="/bff/jobs/{job_id}/actions/{action_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Job lifecycle action (cancel, retry, archive); command admission returns the final envelope.",
    ),
    # ------------------------------------------------------------------ #
    # Agora core actions (BFF-LUV-GAP-006)
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="AgoraSignalFeedback",
        entity_type="AgoraSignal",
        endpoint="/bff/agora/signals/{signal_id}/feedback",
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "reviewer", "approver"],
        description="Record operator feedback on an Agora signal and emit the corresponding audit record.",
    ),
    BffActionCatalogEntry(
        action_id="AgoraMessageAction",
        entity_type="AgoraMessage",
        endpoint="/bff/agora/messages/{message_id}/actions/{action_id}",
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "reviewer", "approver"],
        description="Generic Agora message action such as cite, annotate, pin, or create a handoff.",
    ),
    BffActionCatalogEntry(
        action_id="AgoraInsightAction",
        entity_type="AgoraInsight",
        endpoint="/bff/agora/insights/{insight_id}/actions/{action_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "reviewer", "approver"],
        description="Generic Agora insight action such as attach strategy, dismiss, promote, or convert to training.",
    ),
    BffActionCatalogEntry(
        action_id="AgoraMemoryAction",
        entity_type="AgoraMemory",
        endpoint="/bff/agora/memory/{memory_id}/actions/{action_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "reviewer", "approver"],
        description="Generic Agora memory action such as approve, reject, merge, or quarantine.",
    ),
    # ------------------------------------------------------------------ #
    # Execute-plans semantic command bridge (BFF-LUV-SEM-002)
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="CreateDeployment",
        entity_type="Deployment",
        endpoint="/bff/deployments",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Create a deployment command receipt through the BFF command store without enabling live broker side effects.",
    ),
    BffActionCatalogEntry(
        action_id="PatchDeployment",
        entity_type="Deployment",
        endpoint="/bff/deployments/{deployment_id}",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Patch a deployment command receipt through the BFF command store.",
    ),
    BffActionCatalogEntry(
        action_id="PatchRebalance",
        entity_type="Rebalance",
        endpoint="/bff/rebalances/{rebalance_id}",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Patch a rebalance command receipt through the BFF command store.",
    ),
    BffActionCatalogEntry(
        action_id="AuditExport",
        entity_type="AuditExport",
        endpoint="/bff/audit/export",
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "reviewer", "approver"],
        description="Submit an audit export command receipt backed by the BFF command store.",
    ),
    BffActionCatalogEntry(
        action_id="CreateConfirmToken",
        entity_type="ConfirmToken",
        endpoint="/bff/confirm-tokens",
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Create an operator confirmation token receipt backed by the command store.",
    ),
    BffActionCatalogEntry(
        action_id="DeleteConfirmToken",
        entity_type="ConfirmToken",
        endpoint="/bff/confirm-tokens/{tokenId}",
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Delete an operator confirmation token receipt backed by the command store.",
    ),
    BffActionCatalogEntry(
        action_id="RedeemConfirmToken",
        entity_type="ConfirmToken",
        endpoint="/bff/confirm-tokens/{tokenId}/redeem",
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Redeem an operator confirmation token receipt backed by the command store.",
    ),
    BffActionCatalogEntry(
        action_id="V5InterventionAction",
        entity_type="SentinelIntervention",
        endpoint="/bff/v5/interventions/{intervention_id}/{action_id}",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Submit a v5 intervention lifecycle command receipt without bypassing governance preconditions.",
    ),
    BffActionCatalogEntry(
        action_id="DecideV5Intervention",
        entity_type="SentinelIntervention",
        endpoint="/bff/v5/interventions/{intervention_id}/decide",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Record a v5 intervention decision through the canonical command admission receipt.",
    ),
    BffActionCatalogEntry(
        action_id="SentinelFindingStatus",
        entity_type="SentinelFinding",
        endpoint="/bff/v5/sentinel/findings/{finding_id}/status",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=10,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Record a sentinel finding status command receipt backed by the BFF command store.",
    ),
    BffActionCatalogEntry(
        action_id="SentinelRemediationBuild",
        entity_type="SentinelRemediation",
        endpoint="/bff/v5/sentinel/remediation/build",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=10,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Build a sentinel remediation command receipt without executing live remediation.",
    ),
    BffActionCatalogEntry(
        action_id="SentinelRemediationExecute",
        entity_type="SentinelRemediation",
        endpoint="/bff/v5/sentinel/remediation/{actionId}/execute",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Submit a sentinel remediation execution command receipt without enabling live capital side effects.",
    ),
    # ------------------------------------------------------------------ #
    # P0 lifecycle actions (BFF-WRITE-P0-LIFECYCLE)
    # ------------------------------------------------------------------ #
    BffActionCatalogEntry(
        action_id="AdvanceLifecycle",
        entity_type="Persona",
        endpoint="/bff/personas/{persona_id}/actions/AdvanceLifecycle",
        risk_level=RiskLevel.HIGH,
        requires_approval=True,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["persona_operator", "live_owner_approver"],
        description="Advance persona lifecycle state: draft → paper_owner → live_owner → retired. Confirm token required; live_owner_approver role required when target=live_owner.",
    ),
    BffActionCatalogEntry(
        action_id="ApprovePool",
        entity_type="CapitalPool",
        endpoint="/bff/capital-pools/{pool_id}/actions/ApprovePool",
        risk_level=RiskLevel.HIGH,
        requires_approval=True,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["treasury_approver"],
        description="Approve a capital pool draft → approved (one-way). Memo ≥8 chars required.",
    ),
    BffActionCatalogEntry(
        action_id="Observe",
        entity_type="Persona",
        endpoint="/bff/v1/commands",
        risk_level=RiskLevel.LOW,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=False,
        required_roles=["operator", "reviewer", "approver"],
        description="Observe persona metrics, logs, and telemetry status.",
    ),
    BffActionCatalogEntry(
        action_id="RequestReview",
        entity_type="Review",
        endpoint="/bff/v1/commands",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=10,
        idempotency_required=True,
        required_roles=["operator"],
        description="Request a formal human review packet creation for a persona.",
    ),
    BffActionCatalogEntry(
        action_id="PausePaperRuntime",
        entity_type="Runtime",
        endpoint="/bff/v1/commands",
        risk_level=RiskLevel.HIGH,
        requires_approval=False,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator"],
        description="Pause a paper runtime; stops order execution.",
    ),
    BffActionCatalogEntry(
        action_id="ResumePaperRuntime",
        entity_type="Runtime",
        endpoint="/bff/v1/commands",
        risk_level=RiskLevel.HIGH,
        requires_approval=True,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=30,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Resume a paused paper runtime; resumes order execution.",
    ),
    BffActionCatalogEntry(
        action_id="Demote",
        entity_type="Persona",
        endpoint="/bff/v1/commands",
        risk_level=RiskLevel.HIGH,
        requires_approval=True,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Demote or retire a persona from active allocation.",
    ),
    BffActionCatalogEntry(
        action_id="PromoteCandidate",
        entity_type="Persona",
        endpoint="/bff/v1/commands",
        risk_level=RiskLevel.HIGH,
        requires_approval=True,
        requires_confirm_token=True,
        requires_two_man=False,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Promote a candidate persona to paper_running or canary status.",
    ),
    BffActionCatalogEntry(
        action_id="RebalanceProposal",
        entity_type="Rebalance",
        endpoint="/bff/v1/commands",
        risk_level=RiskLevel.MEDIUM,
        requires_approval=False,
        requires_confirm_token=False,
        requires_two_man=False,
        cooldown_seconds=10,
        idempotency_required=True,
        required_roles=["operator"],
        description="Propose a new asset/portfolio rebalance configuration.",
    ),
    BffActionCatalogEntry(
        action_id="ApprovedApply",
        entity_type="Rebalance",
        endpoint="/bff/v1/commands",
        risk_level=RiskLevel.HIGH,
        requires_approval=True,
        requires_confirm_token=True,
        requires_two_man=True,
        cooldown_seconds=60,
        idempotency_required=True,
        required_roles=["operator", "approver"],
        description="Apply an approved rebalance or deployment change to live systems.",
    ),
    BffActionCatalogEntry(
        action_id="EmergencyContainment",
        entity_type="Persona",
        endpoint="/bff/v1/commands",
        risk_level=RiskLevel.CRITICAL,
        requires_approval=True,
        requires_confirm_token=True,
        requires_two_man=True,
        cooldown_seconds=0,
        idempotency_required=True,
        required_roles=["operator", "reviewer", "approver"],
        description="Immediately reduce exposure or pause runtime execution under threat.",
    ),
]

# Build an O(1) lookup by action_id
_CATALOG_INDEX: dict[str, BffActionCatalogEntry] = {
    e.action_id: e for e in _CATALOG_ENTRIES
}


def get_action_catalog() -> BffActionCatalogResponse:
    """Return the full canonical action catalog as a response object."""
    return BffActionCatalogResponse(catalog=_CATALOG_ENTRIES)


def get_catalog_entry(action_id: str) -> BffActionCatalogEntry | None:
    """Return a single catalog entry by action_id, or None if unknown."""
    return _CATALOG_INDEX.get(action_id)


def catalog_action_ids() -> frozenset[str]:
    """Return the set of all catalogued action_id values."""
    return frozenset(_CATALOG_INDEX.keys())
