"""StrategySpec contract models, normalization, patching, and version comparison."""

from .patching import (
    ALLOWED_OPS,
    ALLOWED_TOP_LEVEL_PREFIXES,
    FORBIDDEN_PATHS,
    PATCH_FORMAT_VERSION,
    PatchBaseHashMismatchError,
    PatchError,
    PatchOperationError,
    PatchPathForbiddenError,
    PatchPolicyInvalidError,
    PatchResultSchemaInvalidError,
    apply_patch,
    apply_patch_validated,
    compute_document_sha256,
    validate_operations,
)
from .version_compare import (
    MAX_CANDIDATE_VERSIONS,
    VALID_EVIDENCE_CLASSES,
    VALID_GATES,
    VALID_READINESS_STATES,
    VersionCompareError,
    VersionCompareLimitExceededError,
    build_recommendation,
    build_version_compare,
    compute_field_diffs,
    compute_metric_diffs,
    compute_readiness_diffs,
)
from .workshop_projection import (
    WorkshopProjection,
    WorkshopVersionLink,
    build_projection,
    build_version_link,
    compute_patch_base,
    latest_version,
    select_version,
)
from .models import (
    CodeRef,
    DataDependency,
    EvidenceRef,
    EvaluationPlan,
    ExecutionProfile,
    Governance,
    MarketScope,
    Provenance,
    StrategyDataDependencyKind,
    StrategyEvidenceRefType,
    StrategyExecutionModeHint,
    StrategyLifecycleState,
    StrategyQuantityType,
    StrategySourceKind,
    StrategySpec,
    StrategySpecValidationError,
    load_strategy_spec_schema,
    strategy_spec_schema_path,
    validate_strategy_spec,
    validate_strategy_spec_payload,
)
from .lineage import (
    StrategySpecLineageError,
    StrategySpecLineageRefs,
    attach_lineage_refs_to_strategy_spec_payload,
    build_strategy_spec_lineage_refs,
)
from .normalizer import (
    NormalizationResult,
    StrategySpecNormalizationError,
    StrategySpecNormalizer,
)

__all__ = [
    # patching
    "ALLOWED_OPS",
    "ALLOWED_TOP_LEVEL_PREFIXES",
    "FORBIDDEN_PATHS",
    "PATCH_FORMAT_VERSION",
    "PatchBaseHashMismatchError",
    "PatchError",
    "PatchOperationError",
    "PatchPathForbiddenError",
    "PatchPolicyInvalidError",
    "PatchResultSchemaInvalidError",
    "apply_patch",
    "apply_patch_validated",
    "compute_document_sha256",
    "validate_operations",
    # version_compare
    "MAX_CANDIDATE_VERSIONS",
    "VALID_EVIDENCE_CLASSES",
    "VALID_GATES",
    "VALID_READINESS_STATES",
    "VersionCompareError",
    "VersionCompareLimitExceededError",
    "build_recommendation",
    "build_version_compare",
    "compute_field_diffs",
    "compute_metric_diffs",
    "compute_readiness_diffs",
    # workshop_projection
    "WorkshopProjection",
    "WorkshopVersionLink",
    "build_projection",
    "build_version_link",
    "compute_patch_base",
    "latest_version",
    "select_version",
    # models / lineage / normalizer
    "CodeRef",
    "DataDependency",
    "EvidenceRef",
    "EvaluationPlan",
    "ExecutionProfile",
    "Governance",
    "MarketScope",
    "NormalizationResult",
    "Provenance",
    "StrategyEvidenceRefType",
    "StrategyDataDependencyKind",
    "StrategyExecutionModeHint",
    "StrategyLifecycleState",
    "StrategySpecNormalizationError",
    "StrategySpecNormalizer",
    "StrategyQuantityType",
    "StrategySourceKind",
    "StrategySpec",
    "StrategySpecLineageError",
    "StrategySpecLineageRefs",
    "StrategySpecValidationError",
    "attach_lineage_refs_to_strategy_spec_payload",
    "build_strategy_spec_lineage_refs",
    "load_strategy_spec_schema",
    "strategy_spec_schema_path",
    "validate_strategy_spec",
    "validate_strategy_spec_payload",
]
