export interface Strategy { id: string; [k: string]: unknown }
export interface Persona { id: string; [k: string]: unknown }
export interface CapitalPool { id: string; [k: string]: unknown }
export interface RankingFormula { id: string; [k: string]: unknown }
export interface Rebalance { id: string; [k: string]: unknown }
export interface Deployment { id: string; [k: string]: unknown }
export interface EvolutionProgram { id: string; [k: string]: unknown }
export interface ResearchExperiment { id: string; [k: string]: unknown }
export interface Artifact { id: string; [k: string]: unknown }
export interface Tool { id: string; [k: string]: unknown }
export interface McpServer { id: string; [k: string]: unknown }
export interface McpTool { id: string; [k: string]: unknown }
export interface Skill { id: string; [k: string]: unknown }
export interface Channel { id: string; [k: string]: unknown }
export interface Job { id: string; [k: string]: unknown }
export interface Runtime { id: string; [k: string]: unknown }
export interface Alert { id: string; [k: string]: unknown }
export interface Incident { id: string; [k: string]: unknown }
export interface ApprovalRequest { id: string; [k: string]: unknown }
export interface AuditEvent { id: string; [k: string]: unknown }
