from __future__ import annotations

import os
import stat
import subprocess
from pathlib import Path

from adapters.base import BaseAdapter, DeliveryCapability, DeliveryRequest, DeliveryResult
from common import (
    agent_config_for,
    command_exists,
    delivery_workspace_root,
    durable_write_bytes,
    ensure_parent,
    new_runtime_id,
    normalize_agent_id,
    relpath,
)
from runtime_state import runtime_state_lock


def _read_regular_file(path: Path) -> bytes:
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    descriptor = os.open(path, flags)
    try:
        descriptor_stat = os.fstat(descriptor)
        path_stat = path.lstat()
        if (
            not stat.S_ISREG(descriptor_stat.st_mode)
            or stat.S_ISLNK(path_stat.st_mode)
            or path_stat.st_dev != descriptor_stat.st_dev
            or path_stat.st_ino != descriptor_stat.st_ino
        ):
            raise RuntimeError(f"file inbox data leaf changed during readback: {path}")
        chunks: list[bytes] = []
        while True:
            chunk = os.read(descriptor, 1024 * 1024)
            if not chunk:
                break
            chunks.append(chunk)
        after_stat = path.lstat()
        if (
            stat.S_ISLNK(after_stat.st_mode)
            or after_stat.st_dev != descriptor_stat.st_dev
            or after_stat.st_ino != descriptor_stat.st_ino
        ):
            raise RuntimeError(f"file inbox data leaf changed during readback: {path}")
        return b"".join(chunks)
    finally:
        os.close(descriptor)


def _write_inbox_locked(path: Path, body: str) -> None:
    try:
        existing_stat = path.lstat()
    except FileNotFoundError:
        existing_stat = None
    if existing_stat is not None and stat.S_ISLNK(existing_stat.st_mode):
        raise RuntimeError(f"file inbox data leaf cannot be a symlink: {path}")
    if existing_stat is not None and not stat.S_ISREG(existing_stat.st_mode):
        raise RuntimeError(f"file inbox data leaf must be a regular file: {path}")
    payload = body.encode("utf-8")
    durable_write_bytes(path, payload)
    if _read_regular_file(path) != payload:
        raise RuntimeError(f"file inbox readback mismatch: {path}")


class FileInboxAdapter(BaseAdapter):
    name = "file_inbox"

    def capability(self, agent_id: str) -> DeliveryCapability:
        return DeliveryCapability(
            adapter=self.name,
            supported=True,
            requires_manual_confirmation=True,
            can_auto_deliver=False,
            can_auto_approve_edits=False,
            delivery_mode="file_inbox",
            verified="verified",
            host="workspace file + VS Code CLI",
            notes="Writes a minimal inbox file and can optionally surface it in the current VS Code window.",
        )

    def deliver(self, request: DeliveryRequest) -> DeliveryResult:
        with runtime_state_lock(self.config, shared=False, nonblocking=False):
            return self._deliver_locked(request)

    def _deliver_locked(self, request: DeliveryRequest) -> DeliveryResult:
        agent = agent_config_for(self.config, request.agent_id)
        provider = self.config.get("providers", {}).get(agent.get("provider", request.provider), {})
        inbox_settings = provider.get("file_inbox", {})
        inbox_map = inbox_settings.get("agent_paths", {}) or {}
        inbox_value = agent.get("file_inbox_path") or inbox_map.get(agent.get("id")) or inbox_settings.get("path")
        inbox_path = Path(inbox_value or f".llm-inbox/{normalize_agent_id(request.agent_id)}.md")
        workspace_root = delivery_workspace_root(self.config, request.metadata)
        if not inbox_path.is_absolute():
            inbox_path = workspace_root / inbox_path
        ensure_parent(inbox_path)
        body = "\n".join(
            [
                "<!-- Generated by .orchestrator. Shared state remains the source of truth. -->",
                f"# Wake-up for {agent.get('display_name', request.agent_id)}",
                "",
                request.message.strip(),
                "",
                "## Context Files",
                *(f"- `{path}`" for path in request.context_files),
            ]
        ).rstrip() + "\n"
        _write_inbox_locked(inbox_path, body)

        command: list[str] = []
        if inbox_settings.get("open_in_vscode", False) and command_exists("code"):
            command = ["code", "-r", str(inbox_path)]
            subprocess.Popen(
                command,
                cwd=str(workspace_root),
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )

        return DeliveryResult(
            ok=True,
            adapter=self.name,
            mode="file_inbox",
            target=agent.get("display_name", request.agent_id),
            auto_delivered=False,
            manual_confirmation_required=True,
            notes=f"Inbox written to {relpath(inbox_path)}",
            command=command,
            payload_path=str(inbox_path),
            run_id=new_runtime_id("inbox"),
        )
