"""Canary proof dry-run API with no live side effects.

The dry-run command exercises the EP5 canary proof path in either
``validate_only`` or ``sandbox`` mode, then emits an A2.2-shaped proof packet
and the underlying PromotionReadinessPacket generated by EP5-005.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Literal, Mapping

from fastapi import APIRouter, FastAPI, HTTPException, status
from pydantic import BaseModel, ConfigDict, Field

from services.governance.ep5_proof.packet_generator import (
    PROOF_FLAG_CANARY_RUNTIME_STARTED,
    PROOF_FLAG_LIVE_CAPITAL_SIDE_EFFECTS,
    PROOF_FLAG_ORDER_ROUTE_MODE,
    PROOF_FLAG_RUNTIME_HEARTBEAT_RECEIVED,
    PROOF_FLAG_TELEMETRY_INGESTED,
    EP5ProofGeneratorError,
    generate_ep5_proof_packet,
)

DRY_RUN_PACKET_VERSION = "2026-05-19.A2.2.dry-run"
SAFE_DRY_RUN_MODES = {"validate_only", "sandbox"}


class EP5DryRunError(ValueError):
    """Raised when a dry-run request would leave the no-live-side-effect boundary."""


class CanaryDryRunRequest(BaseModel):
    """POST /api/v1/ep5/proofs/dry-run request body."""

    model_config = ConfigDict(extra="forbid")

    proof_id: str | None = None
    promotion_readiness_packet_id: str | None = None
    run_id: str | None = None
    persona_id: str
    runtime_id: str
    runtime_binding_id: str
    artifact_id: str
    deployment_plan_id: str
    environment: Literal["canary"] = "canary"
    mode: Literal["validate_only", "sandbox"] = "validate_only"
    order_route_mode: Literal["validate_only", "sandbox"] | None = None
    runtime_started: bool = True
    runtime_heartbeat_received: bool = True
    telemetry_ingested: bool = True
    rollback_drill_completed: bool = False
    kill_switch_demo_completed: bool = False
    audit_events_recorded: bool = True
    incident_path_tested: bool = False
    evidence_refs: list[str] = Field(default_factory=list)
    started_at: str | None = None
    ended_at: str | None = None
    live_capital_side_effects: Literal[False] = False


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _new_id(prefix: str) -> str:
    return f"{prefix}-{uuid.uuid4().hex[:12]}"


def _required_text(value: str | None, field_name: str) -> str:
    text = str(value or "").strip()
    if not text:
        raise EP5DryRunError(f"{field_name} is required")
    return text


def _request_from_payload(payload: Mapping[str, Any] | CanaryDryRunRequest) -> CanaryDryRunRequest:
    if isinstance(payload, CanaryDryRunRequest):
        return payload
    return CanaryDryRunRequest.model_validate(dict(payload))


def run_canary_dry_run(payload: Mapping[str, Any] | CanaryDryRunRequest) -> dict[str, Any]:
    """Run the no-side-effect canary proof path and return a dry-run packet.

    This function is pure. It performs no broker calls and no writes. The only
    execution outcome it can produce for the protected side-effect field is
    ``live_capital_side_effects: false``.
    """
    request = _request_from_payload(payload)
    mode = request.mode
    order_route_mode = request.order_route_mode or mode

    if mode not in SAFE_DRY_RUN_MODES:
        raise EP5DryRunError(f"unsupported dry-run mode: {mode!r}")
    if order_route_mode not in SAFE_DRY_RUN_MODES:
        raise EP5DryRunError(
            f"dry-run order_route_mode must be validate_only or sandbox: {order_route_mode!r}"
        )
    if order_route_mode != mode:
        raise EP5DryRunError("order_route_mode must match dry-run mode")
    if request.live_capital_side_effects is not False:
        raise EP5DryRunError("live_capital_side_effects must be false for EP5 dry-run")

    proof_id = _required_text(request.proof_id or _new_id("ep5-proof-dry-run"), "proof_id")
    readiness_packet_id = _required_text(
        request.promotion_readiness_packet_id or _new_id("prp-dry-run"),
        "promotion_readiness_packet_id",
    )
    run_id = _required_text(request.run_id or _new_id("canary-dry-run"), "run_id")
    persona_id = _required_text(request.persona_id, "persona_id")
    runtime_id = _required_text(request.runtime_id, "runtime_id")
    runtime_binding_id = _required_text(request.runtime_binding_id, "runtime_binding_id")
    artifact_id = _required_text(request.artifact_id, "artifact_id")
    deployment_plan_id = _required_text(request.deployment_plan_id, "deployment_plan_id")
    started_at = request.started_at or _utc_now_iso()
    ended_at = request.ended_at or started_at

    heartbeat_count = 1 if request.runtime_heartbeat_received else 0
    telemetry_event_count = 1 if request.telemetry_ingested else 0
    canary_run = {
        "run_id": run_id,
        "persona_id": persona_id,
        "runtime_id": runtime_id,
        "environment": request.environment,
        "deployment_stage": "canary",
        "runtime_started": request.runtime_started,
        "heartbeat_count": heartbeat_count,
        "order_route_mode": order_route_mode,
        "telemetry_event_count": telemetry_event_count,
        "result": "pass",
        "started_at": started_at,
        "finished_at": ended_at,
        "live_capital_side_effects": False,
        "broker_production_live_enabled": False,
    }

    try:
        readiness_packet = generate_ep5_proof_packet(
            canary_run,
            packet_id=readiness_packet_id,
            generated_by="EP5-006-V2/dry_run",
            source_task_id="EP5-006-V2",
        )
    except EP5ProofGeneratorError as exc:
        raise EP5DryRunError(str(exc)) from exc

    blocking_reasons = [item.code for item in readiness_packet.blocking_reasons]
    status_value = "passed" if readiness_packet.can_proceed else "failed"
    proof = {
        "canary_runtime_started": readiness_packet.flags.values[PROOF_FLAG_CANARY_RUNTIME_STARTED],
        "runtime_heartbeat_received": readiness_packet.flags.values[PROOF_FLAG_RUNTIME_HEARTBEAT_RECEIVED],
        "order_route_mode": order_route_mode,
        "live_capital_side_effects": readiness_packet.flags.values[PROOF_FLAG_LIVE_CAPITAL_SIDE_EFFECTS],
        "telemetry_ingested": readiness_packet.flags.values[PROOF_FLAG_TELEMETRY_INGESTED],
        "rollback_drill_completed": request.rollback_drill_completed,
        "kill_switch_demo_completed": request.kill_switch_demo_completed,
        "audit_events_recorded": request.audit_events_recorded,
        "incident_path_tested": request.incident_path_tested,
    }
    ep5_proof_packet = {
        "packet_id": proof_id,
        "packet_version": DRY_RUN_PACKET_VERSION,
        "promotion_readiness_packet_id": readiness_packet.packet_id,
        "environment": request.environment,
        "started_at": started_at,
        "ended_at": ended_at,
        "status": status_value,
        "runtime": {
            "runtime_id": runtime_id,
            "runtime_binding_id": runtime_binding_id,
            "artifact_id": artifact_id,
            "deployment_plan_id": deployment_plan_id,
        },
        "proof": proof,
        "result": {
            "pass": readiness_packet.can_proceed,
            "blocking_reasons": blocking_reasons,
            "evidence_refs": list(request.evidence_refs),
        },
    }

    return {
        "dry_run_id": proof_id,
        "mode": mode,
        "status": status_value,
        "live_capital_side_effects": False,
        "canary_run": canary_run,
        "proof_packet": ep5_proof_packet,
        "promotion_readiness_packet": readiness_packet.to_dict(),
    }


router = APIRouter()


@router.post("/api/v1/ep5/proofs/dry-run", status_code=status.HTTP_200_OK)
async def post_ep5_proofs_dry_run(body: CanaryDryRunRequest) -> dict[str, Any]:
    try:
        return run_canary_dry_run(body)
    except EP5DryRunError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc


def create_app() -> FastAPI:
    app = FastAPI(title="Pantheon EP5 Proof Dry-Run API", version="0.1.0")
    app.include_router(router)
    return app


app = create_app()
