"""Source connector models."""

from .base import (
    AuthPolicy,
    AuthType,
    ConnectorMode,
    ConnectorStatus,
    IngestEvent,
    IngestRun,
    IngestRunStatus,
    LicensePolicy,
    RateLimitPolicy,
    SecretRef,
    SourceConnector,
    SourceConnectorProvider,
    SourceEvidenceError,
    SourceMetadata,
    SourceRecord,
    SourceRecordStatus,
    SourceType,
)
from .examples import ExternalFeedProviderExample, StaticRecordsProviderExample, example_provider_catalog
from .finmind_taiwan import (
    FinMindTaiwanBrokerBulkBackfillAdapter,
    FinMindTaiwanBrokerDailyReportAdapter,
    FinMindTaiwanDatasetAdapter,
)
from .paper import OpenAlexPaperIngestAdapter
from .repo_allowlist import RepoAllowlistEntry, RepoAllowlistProvider
from .taiwan_market import MopsSourceIngestAdapter, TejSourceIngestAdapter
from .taiwan_official import (
    TAIWAN_OFFICIAL_ENDPOINTS,
    TW_OFFICIAL_CONNECTOR_ID,
    TaiwanOfficialMarketDatasetAdapter,
)
from .us_paid_broker import (
    ALPHA_VANTAGE_US_DAILY_CONNECTOR_ID,
    IBKR_READBACK_CONNECTOR_ID,
    POLYGON_US_DAILY_CONNECTOR_ID,
    SHIOAJI_READBACK_CONNECTOR_ID,
    AlphaVantageUsEquityDailyAdapter,
    IbkrBrokerReadbackAdapter,
    PolygonUsEquityDailyAdapter,
    ShioajiBrokerReadbackAdapter,
)
from .us_public import (
    FINRA_SHORT_SALE_CONNECTOR_ID,
    FRED_CONNECTOR_ID,
    SEC_EDGAR_CONNECTOR_ID,
    STOOQ_DAILY_OHLCV_CONNECTOR_ID,
    FinraShortSaleAdapter,
    FredMacroSeriesAdapter,
    SecEdgarFilingAdapter,
    StooqDailyOhlcvAdapter,
)
from .yahoo_taiwan import (
    AnueTaiwanRssAdapter,
    YahooTaiwanBrokerTopAdapter,
    YahooTaiwanRssAdapter,
    parse_yahoo_broker_trading_html,
)

__all__ = [
    "ALPHA_VANTAGE_US_DAILY_CONNECTOR_ID",
    "AlphaVantageUsEquityDailyAdapter",
    "AuthPolicy",
    "AuthType",
    "AnueTaiwanRssAdapter",
    "ConnectorMode",
    "ConnectorStatus",
    "IngestEvent",
    "IngestRun",
    "IngestRunStatus",
    "LicensePolicy",
    "RateLimitPolicy",
    "SecretRef",
    "SourceConnector",
    "SourceConnectorProvider",
    "SourceEvidenceError",
    "SourceMetadata",
    "SourceRecord",
    "SourceRecordStatus",
    "SourceType",
    "ExternalFeedProviderExample",
    "FINRA_SHORT_SALE_CONNECTOR_ID",
    "FinMindTaiwanBrokerBulkBackfillAdapter",
    "FinMindTaiwanBrokerDailyReportAdapter",
    "FinMindTaiwanDatasetAdapter",
    "FinraShortSaleAdapter",
    "FRED_CONNECTOR_ID",
    "FredMacroSeriesAdapter",
    "IBKR_READBACK_CONNECTOR_ID",
    "IbkrBrokerReadbackAdapter",
    "OpenAlexPaperIngestAdapter",
    "POLYGON_US_DAILY_CONNECTOR_ID",
    "PolygonUsEquityDailyAdapter",
    "RepoAllowlistEntry",
    "RepoAllowlistProvider",
    "SEC_EDGAR_CONNECTOR_ID",
    "SHIOAJI_READBACK_CONNECTOR_ID",
    "STOOQ_DAILY_OHLCV_CONNECTOR_ID",
    "SecEdgarFilingAdapter",
    "ShioajiBrokerReadbackAdapter",
    "StaticRecordsProviderExample",
    "StooqDailyOhlcvAdapter",
    "TAIWAN_OFFICIAL_ENDPOINTS",
    "TW_OFFICIAL_CONNECTOR_ID",
    "MopsSourceIngestAdapter",
    "TaiwanOfficialMarketDatasetAdapter",
    "TejSourceIngestAdapter",
    "YahooTaiwanBrokerTopAdapter",
    "YahooTaiwanRssAdapter",
    "parse_yahoo_broker_trading_html",
    "example_provider_catalog",
]
