#!/usr/bin/env bash
set -euo pipefail

APP_USER="${PANTHEON_APP_DB_USER:-pantheon_app}"
APP_PASS="${PANTHEON_APP_DB_PASSWORD:-pantheon_app}"
APP_DB="${PANTHEON_APP_DB_NAME:-pantheon}"
MGMT_AI_USER="${PANTHEON_MANAGEMENT_AI_DB_USER:-pantheon_management_ai}"
MGMT_AI_PASS="${PANTHEON_MANAGEMENT_AI_DB_PASSWORD:-pantheon_management_ai_dev}"
MGMT_AI_DB="${PANTHEON_MANAGEMENT_AI_DB_NAME:-$APP_DB}"
MGMT_AI_SCHEMA="${MANAGEMENT_AI_STORE_SCHEMA:-management_ai}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$body\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_USER}') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${APP_USER}', '${APP_PASS}');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${MGMT_AI_USER}') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${MGMT_AI_USER}', '${MGMT_AI_PASS}');
  END IF;
END
\$body\$;

SELECT format('CREATE DATABASE %I OWNER %I', '${APP_DB}', '${APP_USER}')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${APP_DB}')
\gexec

SELECT format('CREATE DATABASE %I OWNER %I', '${MGMT_AI_DB}', '${MGMT_AI_USER}')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${MGMT_AI_DB}')
\gexec

GRANT ALL PRIVILEGES ON DATABASE "${APP_DB}" TO "${APP_USER}";
ALTER ROLE "${MGMT_AI_USER}" LOGIN PASSWORD '${MGMT_AI_PASS}';
GRANT CONNECT ON DATABASE "${MGMT_AI_DB}" TO "${MGMT_AI_USER}";
GRANT CREATE ON DATABASE "${MGMT_AI_DB}" TO "${MGMT_AI_USER}";
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_DB" <<SQL
ALTER SCHEMA public OWNER TO "${APP_USER}";
GRANT ALL ON SCHEMA public TO "${APP_USER}";
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$MGMT_AI_DB" <<SQL
CREATE SCHEMA IF NOT EXISTS "${MGMT_AI_SCHEMA}" AUTHORIZATION "${MGMT_AI_USER}";
ALTER SCHEMA "${MGMT_AI_SCHEMA}" OWNER TO "${MGMT_AI_USER}";
GRANT USAGE, CREATE ON SCHEMA "${MGMT_AI_SCHEMA}" TO "${MGMT_AI_USER}";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "${MGMT_AI_SCHEMA}" TO "${MGMT_AI_USER}";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA "${MGMT_AI_SCHEMA}" TO "${MGMT_AI_USER}";
ALTER DEFAULT PRIVILEGES FOR ROLE "${MGMT_AI_USER}" IN SCHEMA "${MGMT_AI_SCHEMA}" GRANT ALL PRIVILEGES ON TABLES TO "${MGMT_AI_USER}";
ALTER DEFAULT PRIVILEGES FOR ROLE "${MGMT_AI_USER}" IN SCHEMA "${MGMT_AI_SCHEMA}" GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "${MGMT_AI_USER}";
SQL
