#!/usr/bin/env python3
"""MGMT-SAFE-005 no-live-side-effects assertion smoke.

The smoke is intentionally repo-local. It reads task evidence packets that were
already generated by the paper, sandbox, canary-gate, and OpenClaw denial lanes
and asserts that no current Track E proof opened live order, live capital, or
production-broker side effects.
"""
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
OODA_DIR = REPO_ROOT / "services" / "control-plane" / "ooda"
if str(OODA_DIR) not in sys.path:
    sys.path.insert(0, str(OODA_DIR))

from ooda_loop_packet import (  # noqa: E402
    LoopEnvironment,
    LoopStatus,
    LoopType,
    OodaLoopPacket,
    validate_packet,
)


TASK_ID = "MGMT-SAFE-005"

REQUIRED_EVIDENCE_PATHS = (
    "support/evidence/MGMT-OODA-M2-paper-loop.json",
    "support/evidence/MGMT-PAPER-001-paper-strategy-spec.json",
    "support/evidence/MGMT-PAPER-002-paper-approval-decision.json",
    "support/evidence/MGMT-PAPER-005-paper-telemetry-packet.json",
    "support/evidence/MGMT-PAPER-007-complete-paper-ooda-packet.json",
    "support/evidence/MGMT-BROKER-003/summary.json",
    "support/evidence/MGMT-BROKER-003/no-real-capital-evidence.json",
    "support/evidence/MGMT-SYN-007/synthesis-proof.json",
)

OPTIONAL_EVIDENCE_PATHS = (
    "support/evidence/MGMT-PAPER-003-paper-deployment-plan.json",
    "support/evidence/MGMT-QLIB-002/strategy_spec_packet.json",
    "support/evidence/MGMT-SAFE-003/openclaw-broker-tool-denial-smoke.json",
    "support/evidence/MGMT-SAFE-004/canary-human-gate-smoke.json",
    "support/evidence/MGMT-SAFE-006/command-idempotency-regression.json",
)

MUST_BE_FALSE_FIELDS = {
    "capital_side_effects_allowed",
    "live_capital_side_effects",
    "live_execution_enabled",
    "live_mutation_allowed",
    "live_order_submitted",
    "order_side_effects_allowed",
    "production_broker_enabled",
    "production_live_broker_session_opened",
    "production_live_enabled",
    "production_live_order_submitted",
    "production_live_side_effects_allowed",
    "real_capital_used",
    "real_order_submitted",
}

NON_LIVE_GUARD_ERROR = (
    "act.live_capital_side_effects must be false in dev, paper, sandbox, and canary environments"
)


@dataclass
class SmokeRow:
    row: str
    status: str
    evidence: dict[str, Any] = field(default_factory=dict)
    error: str = ""


def _pass(row: str, evidence: dict[str, Any] | None = None) -> SmokeRow:
    return SmokeRow(row=row, status="passed", evidence=evidence or {})


def _fail(row: str, error: str, evidence: dict[str, Any] | None = None) -> SmokeRow:
    return SmokeRow(row=row, status="failed", error=error, evidence=evidence or {})


def _check(row: str, condition: bool, evidence: dict[str, Any], error: str) -> SmokeRow:
    return _pass(row, evidence) if condition else _fail(row, error, evidence)


def _repo_path(path: str | Path) -> Path:
    candidate = Path(path)
    if candidate.is_absolute():
        return candidate
    return REPO_ROOT / candidate


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _iter_nodes(value: Any, path: str = "$") -> Iterable[tuple[str, Any, str | None]]:
    if isinstance(value, Mapping):
        for key, item in value.items():
            child_path = f"{path}.{key}" if path else str(key)
            yield child_path, item, str(key)
            yield from _iter_nodes(item, child_path)
    elif isinstance(value, list):
        for index, item in enumerate(value):
            child_path = f"{path}[{index}]"
            yield child_path, item, None
            yield from _iter_nodes(item, child_path)


def _find_side_effect_violations(payload: Any, *, artifact: Path) -> list[dict[str, Any]]:
    violations: list[dict[str, Any]] = []
    for path, value, key in _iter_nodes(payload):
        if key is None or key.lower() not in MUST_BE_FALSE_FIELDS:
            continue
        if value is not False:
            violations.append(
                {
                    "artifact": _display_path(artifact),
                    "path": path,
                    "field": key,
                    "expected": False,
                    "actual": value,
                }
            )
    return violations


def _find_ooda_packets(payload: Any, *, artifact: Path) -> list[tuple[str, dict[str, Any]]]:
    packets: list[tuple[str, dict[str, Any]]] = []
    if isinstance(payload, Mapping):
        packet_id = payload.get("packet_id")
        if isinstance(packet_id, str) and packet_id.startswith("ooda-") and isinstance(payload.get("act"), Mapping):
            packets.append((_display_path(artifact), dict(payload)))
    for path, node, _key in _iter_nodes(payload):
        if not isinstance(node, Mapping):
            continue
        packet_id = node.get("packet_id")
        if isinstance(packet_id, str) and packet_id.startswith("ooda-") and isinstance(node.get("act"), Mapping):
            packets.append((f"{_display_path(artifact)}:{path}", dict(node)))
    seen: set[tuple[str, str]] = set()
    unique: list[tuple[str, dict[str, Any]]] = []
    for location, packet in packets:
        marker = (location, str(packet.get("packet_id")))
        if marker not in seen:
            seen.add(marker)
            unique.append((location, packet))
    return unique


def _scan_evidence(
    required_paths: Sequence[str | Path],
    optional_paths: Sequence[str | Path],
) -> tuple[SmokeRow, dict[str, Any], list[tuple[str, dict[str, Any]]]]:
    loaded: dict[str, Any] = {}
    missing_required: list[str] = []
    missing_optional: list[str] = []
    violations: list[dict[str, Any]] = []
    ooda_packets: list[tuple[str, dict[str, Any]]] = []

    for raw_path in required_paths:
        path = _repo_path(raw_path)
        if not path.exists():
            missing_required.append(_display_path(path))
            continue
        payload = _load_json(path)
        loaded[_display_path(path)] = payload
        violations.extend(_find_side_effect_violations(payload, artifact=path))
        ooda_packets.extend(_find_ooda_packets(payload, artifact=path))

    for raw_path in optional_paths:
        path = _repo_path(raw_path)
        if not path.exists():
            missing_optional.append(_display_path(path))
            continue
        payload = _load_json(path)
        loaded[_display_path(path)] = payload
        violations.extend(_find_side_effect_violations(payload, artifact=path))
        ooda_packets.extend(_find_ooda_packets(payload, artifact=path))

    evidence = {
        "required_artifacts": len(required_paths),
        "required_loaded": len(required_paths) - len(missing_required),
        "optional_loaded": len(optional_paths) - len(missing_optional),
        "missing_required": missing_required,
        "missing_optional": missing_optional,
        "checked_fields": sorted(MUST_BE_FALSE_FIELDS),
        "violation_count": len(violations),
        "violations": violations[:20],
    }
    row = _check(
        "evidence-side-effect-flags-stay-false",
        not missing_required and not violations,
        evidence,
        "required evidence missing or at least one side-effect flag was not false",
    )
    return row, loaded, ooda_packets


def _row_for_ooda_packets(ooda_packets: Sequence[tuple[str, dict[str, Any]]]) -> SmokeRow:
    failures: list[dict[str, Any]] = []
    checked: list[dict[str, Any]] = []
    for location, packet in ooda_packets:
        packet_id = str(packet.get("packet_id") or "")
        environment = str(packet.get("environment") or "")
        act = packet.get("act") if isinstance(packet.get("act"), Mapping) else {}
        live_side_effects = act.get("live_capital_side_effects") if isinstance(act, Mapping) else None
        errors = validate_packet(dict(packet))
        checked.append(
            {
                "location": location,
                "packet_id": packet_id,
                "environment": environment,
                "live_capital_side_effects": live_side_effects,
                "validation_errors": errors,
            }
        )
        if environment != LoopEnvironment.LIVE.value and live_side_effects is not False:
            failures.append(
                {
                    "location": location,
                    "packet_id": packet_id,
                    "environment": environment,
                    "error": "non-live OODA packet has live_capital_side_effects != false",
                }
            )
        if errors:
            failures.append(
                {
                    "location": location,
                    "packet_id": packet_id,
                    "environment": environment,
                    "error": "OODA packet validation failed",
                    "validation_errors": errors,
                }
            )

    return _check(
        "non-live-ooda-packets-validate-without-live-side-effects",
        bool(ooda_packets) and not failures,
        {
            "packet_count": len(ooda_packets),
            "checked": checked,
            "failures": failures,
        },
        "one or more non-live OODA packets allow live side effects or fail validation",
    )


def _row_for_non_live_guard() -> SmokeRow:
    packet = OodaLoopPacket.create(
        loop_type=LoopType.PAPER_STRATEGY,
        environment=LoopEnvironment.PAPER,
        strategy_id="strategy-mgmt-safe-005",
    )
    for status in (LoopStatus.OBSERVING, LoopStatus.ORIENTED, LoopStatus.DECIDED, LoopStatus.ACTED):
        packet.advance(status)
    packet.act.runtime_binding_id = "runtime-binding-mgmt-safe-005"
    packet.act.live_capital_side_effects = True

    payload = packet.to_dict()
    model_errors = validate_packet(payload)
    schema_available = False
    schema_rejected = False
    schema_error = ""
    try:
        import jsonschema

        schema_available = True
        schema_path = OODA_DIR / "ooda_loop_packet.schema.json"
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        try:
            jsonschema.validate(payload, schema)
        except jsonschema.ValidationError as exc:
            schema_rejected = True
            schema_error = exc.message
    except ImportError:
        schema_error = "jsonschema not installed; Python model guard still checked"

    return _check(
        "non-live-guard-rejects-forced-live-side-effect",
        NON_LIVE_GUARD_ERROR in model_errors and (schema_rejected or not schema_available),
        {
            "environment": payload["environment"],
            "live_capital_side_effects": payload["act"]["live_capital_side_effects"],
            "model_errors": model_errors,
            "jsonschema_available": schema_available,
            "schema_rejected": schema_rejected,
            "schema_error": schema_error,
        },
        "non-live OODA guard did not reject live_capital_side_effects=true",
    )


def _row_for_safety_smoke_summaries(loaded: Mapping[str, Any]) -> SmokeRow:
    findings: list[dict[str, Any]] = []
    failures: list[str] = []

    safe_003 = loaded.get("support/evidence/MGMT-SAFE-003/openclaw-broker-tool-denial-smoke.json")
    if isinstance(safe_003, Mapping):
        summary = safe_003.get("summary") if isinstance(safe_003.get("summary"), Mapping) else {}
        assertions = safe_003.get("assertions") if isinstance(safe_003.get("assertions"), Mapping) else {}
        ok = (
            summary.get("smoke_passed") is True
            and summary.get("production_broker_enabled") is False
            and summary.get("live_execution_enabled") is False
            and summary.get("capital_binding_enabled") is False
            and assertions.get("broker_tools_denied_by_adapter_policy") is True
        )
        findings.append({"artifact": "MGMT-SAFE-003", "checked": True, "passed": ok})
        if not ok:
            failures.append("MGMT-SAFE-003 broker/OpenClaw denial smoke is not fail-closed")

    safe_004 = loaded.get("support/evidence/MGMT-SAFE-004/canary-human-gate-smoke.json")
    if isinstance(safe_004, Mapping):
        summary = safe_004.get("summary") if isinstance(safe_004.get("summary"), Mapping) else {}
        assertions = safe_004.get("assertions") if isinstance(safe_004.get("assertions"), Mapping) else {}
        ok = (
            summary.get("smoke_passed") is True
            and summary.get("production_live_order_submitted") is False
            and summary.get("real_capital_used") is False
            and assertions.get("production_live_boundary_must_be_fail_closed") is True
        )
        findings.append({"artifact": "MGMT-SAFE-004", "checked": True, "passed": ok})
        if not ok:
            failures.append("MGMT-SAFE-004 canary human-gate smoke does not prove no live side effects")

    if not findings:
        findings.append({"artifact": "optional-safety-smokes", "checked": False, "passed": True})

    return _check(
        "optional-safety-smoke-summaries-remain-fail-closed",
        not failures,
        {"findings": findings, "failures": failures},
        "; ".join(failures) or "optional safety smoke summary failed",
    )


def run_smoke(
    *,
    required_paths: Sequence[str | Path] = REQUIRED_EVIDENCE_PATHS,
    optional_paths: Sequence[str | Path] = OPTIONAL_EVIDENCE_PATHS,
) -> dict[str, Any]:
    evidence_row, loaded, ooda_packets = _scan_evidence(required_paths, optional_paths)
    rows = [
        evidence_row,
        _row_for_ooda_packets(ooda_packets),
        _row_for_non_live_guard(),
        _row_for_safety_smoke_summaries(loaded),
    ]
    passed = sum(1 for row in rows if row.status == "passed")
    smoke_passed = passed == len(rows)
    evidence_summary = evidence_row.evidence
    return {
        "task_id": TASK_ID,
        "status": "passed" if smoke_passed else "failed",
        "summary": {
            "smoke_passed": smoke_passed,
            "passed": passed,
            "rows": len(rows),
            "required_loaded": evidence_summary["required_loaded"],
            "optional_loaded": evidence_summary["optional_loaded"],
            "side_effect_violation_count": evidence_summary["violation_count"],
            "ooda_packet_count": len(ooda_packets),
            "live_capital_side_effects": False,
            "production_live_order_submitted": False,
            "real_capital_used": False,
            "order_side_effects_allowed": False,
            "capital_side_effects_allowed": False,
        },
        "assertions": {
            "required_evidence_loaded": evidence_row.status == "passed"
            and not evidence_summary["missing_required"],
            "side_effect_flags_all_false": evidence_summary["violation_count"] == 0,
            "non_live_ooda_packets_reject_live_capital_side_effects": rows[1].status == "passed"
            and rows[2].status == "passed",
            "optional_safety_smokes_fail_closed_when_present": rows[3].status == "passed",
        },
        "rows": [asdict(row) for row in rows],
    }


def _print_summary(report: Mapping[str, Any]) -> None:
    summary = report["summary"]
    print(f"No-live-side-effects assertion: {summary['passed']}/{summary['rows']} passed")
    for row in report["rows"]:
        marker = "ok " if row["status"] == "passed" else "err"
        print(f"{marker} {row['row']}")
        if row["error"]:
            print(f"    {row['error']}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run MGMT-SAFE-005 no-live-side-effects assertion smoke.")
    parser.add_argument(
        "--required-evidence",
        action="append",
        default=[],
        help="Required JSON evidence path. May be repeated; defaults to Track E required evidence.",
    )
    parser.add_argument(
        "--optional-evidence",
        action="append",
        default=[],
        help="Optional JSON evidence path. May be repeated; defaults to current safety smoke evidence.",
    )
    parser.add_argument("--json-out", default="", help="Optional path for the JSON evidence report.")
    args = parser.parse_args(argv)

    required = tuple(args.required_evidence) if args.required_evidence else REQUIRED_EVIDENCE_PATHS
    optional = tuple(args.optional_evidence) if args.optional_evidence else OPTIONAL_EVIDENCE_PATHS
    report = run_smoke(required_paths=required, optional_paths=optional)
    if args.json_out:
        out = Path(args.json_out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    _print_summary(report)
    return 0 if report["summary"]["smoke_passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
