#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="${PANTHEON_WORKER_GIT_CONFIG_DIR:-$HOME/.config/pantheon/worker-git}"
ENV_FILE="${PANTHEON_WORKER_GIT_ENV_FILE:-$HOME/.config/pantheon/worker-git.env}"
MODE="auto"

usage() {
  cat <<'USAGE'
Usage: scripts/setup_worker_credentials.sh [--mode ssh|pat|auto]

Configures non-interactive git push credentials for Pantheon background workers.
Secrets are written only to local user-readable files when required; they are
never printed to stdout.

SSH inputs:
  PANTHEON_WORKER_GIT_SSH_KEY_PATH   Existing private key path.
  PANTHEON_WORKER_GIT_SSH_KEY        Private key material to store locally.

PAT inputs:
  PANTHEON_WORKER_GIT_TOKEN          GitHub token to store in a local 0600 file.
  GITHUB_TOKEN                       Fallback token source when the Pantheon env var is absent.
  PANTHEON_WORKER_GIT_USERNAME       Optional username; defaults to x-access-token.

Outputs:
  ~/.config/pantheon/worker-git.env  Non-secret runtime env references.
  ~/.config/pantheon/worker-git/      Local credential helper files.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      MODE="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$MODE" in
  auto|ssh|pat) ;;
  *)
    echo "Invalid --mode '$MODE'; expected ssh, pat, or auto." >&2
    exit 2
    ;;
esac

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
mkdir -p "$(dirname "$ENV_FILE")"

write_env_header() {
  {
    printf '# Pantheon worker git credential references.\n'
    printf '# Generated by scripts/setup_worker_credentials.sh.\n'
    printf '# This file must contain paths/env names only, not raw credential values.\n'
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

write_known_hosts() {
  local known_hosts="$CONFIG_DIR/known_hosts"
  if command -v ssh-keyscan >/dev/null 2>&1; then
    ssh-keyscan -T 5 github.com > "$known_hosts.tmp" 2>/dev/null || true
    if [[ -s "$known_hosts.tmp" ]]; then
      mv "$known_hosts.tmp" "$known_hosts"
      chmod 600 "$known_hosts"
      printf '%s' "$known_hosts"
      return 0
    fi
    rm -f "$known_hosts.tmp"
  fi
  if [[ -f "$known_hosts" ]]; then
    printf '%s' "$known_hosts"
    return 0
  fi
  return 1
}

configure_ssh() {
  local key_path="${PANTHEON_WORKER_GIT_SSH_KEY_PATH:-}"
  if [[ -z "$key_path" && -n "${PANTHEON_WORKER_GIT_SSH_KEY:-}" ]]; then
    key_path="$CONFIG_DIR/id_ed25519"
    set +x
    umask 077
    printf '%s\n' "$PANTHEON_WORKER_GIT_SSH_KEY" > "$key_path"
    chmod 600 "$key_path"
  fi
  if [[ -z "$key_path" ]]; then
    echo "SSH mode requires PANTHEON_WORKER_GIT_SSH_KEY_PATH or PANTHEON_WORKER_GIT_SSH_KEY." >&2
    exit 2
  fi
  if [[ ! -f "$key_path" ]]; then
    echo "SSH private key path is not a file: $key_path" >&2
    exit 2
  fi
  if [[ ! -s "$key_path" ]]; then
    echo "SSH private key path is empty: $key_path" >&2
    exit 2
  fi
  chmod 600 "$key_path"

  local known_hosts=""
  known_hosts="$(write_known_hosts || true)"

  write_env_header
  {
    printf 'PANTHEON_WORKER_GIT_AUTH_MODE=ssh\n'
    printf 'PANTHEON_WORKER_GIT_SSH_KEY_PATH=%s\n' "$key_path"
    if [[ -n "$known_hosts" ]]; then
      printf 'PANTHEON_WORKER_GIT_KNOWN_HOSTS=%s\n' "$known_hosts"
    fi
  } >> "$ENV_FILE"
}

configure_pat() {
  local token_file="$CONFIG_DIR/github-token"
  local askpass="$CONFIG_DIR/git-askpass.sh"
  local username="${PANTHEON_WORKER_GIT_USERNAME:-x-access-token}"

  if [[ -n "${PANTHEON_WORKER_GIT_TOKEN:-}" ]]; then
    set +x
    umask 077
    printf '%s' "$PANTHEON_WORKER_GIT_TOKEN" > "$token_file"
    chmod 600 "$token_file"
  elif [[ -n "${GITHUB_TOKEN:-}" ]]; then
    set +x
    umask 077
    printf '%s' "$GITHUB_TOKEN" > "$token_file"
    chmod 600 "$token_file"
  elif [[ ! -s "$token_file" ]]; then
    echo "PAT mode requires PANTHEON_WORKER_GIT_TOKEN, GITHUB_TOKEN, or existing $token_file." >&2
    exit 2
  fi

  cat > "$askpass" <<'ASKPASS'
#!/usr/bin/env sh
set -eu

case "${1:-}" in
  *Username*|*username*)
    printf '%s\n' "${PANTHEON_WORKER_GIT_USERNAME:-x-access-token}"
    ;;
  *Password*|*password*)
    if [ -n "${PANTHEON_WORKER_GIT_TOKEN_FILE:-}" ] && [ -f "$PANTHEON_WORKER_GIT_TOKEN_FILE" ]; then
      cat "$PANTHEON_WORKER_GIT_TOKEN_FILE"
    elif [ -n "${PANTHEON_WORKER_GIT_TOKEN:-}" ]; then
      printf '%s' "$PANTHEON_WORKER_GIT_TOKEN"
    elif [ -n "${GITHUB_TOKEN:-}" ]; then
      printf '%s' "$GITHUB_TOKEN"
    else
      exit 2
    fi
    ;;
  *)
    printf '\n'
    ;;
esac
ASKPASS
  chmod 700 "$askpass"

  write_env_header
  {
    printf 'PANTHEON_WORKER_GIT_AUTH_MODE=pat\n'
    printf 'PANTHEON_WORKER_GIT_ASKPASS=%s\n' "$askpass"
    printf 'PANTHEON_WORKER_GIT_TOKEN_FILE=%s\n' "$token_file"
    printf 'PANTHEON_WORKER_GIT_USERNAME=%s\n' "$username"
  } >> "$ENV_FILE"
}

if [[ "$MODE" == "auto" ]]; then
  if [[ -n "${PANTHEON_WORKER_GIT_SSH_KEY_PATH:-}" || -n "${PANTHEON_WORKER_GIT_SSH_KEY:-}" ]]; then
    MODE="ssh"
  else
    MODE="pat"
  fi
fi

case "$MODE" in
  ssh) configure_ssh ;;
  pat) configure_pat ;;
esac

PANTHEON_WORKER_GIT_ENV_FILE="$ENV_FILE" python3 "$ROOT_DIR/.orchestrator/auth_loader.py" --json >/dev/null

printf 'Configured Pantheon worker git credentials: mode=%s env_file=%s\n' "$MODE" "$ENV_FILE"
