"""Typed query and command ports for the Deployment domain."""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, Sequence, runtime_checkable


@runtime_checkable
class DeploymentQueries(Protocol):
    """Read interface required by DeploymentService and deployment routes."""

    def list_registry_entries(self) -> Sequence[Dict[str, Any]]: ...
    def get_binding(self, binding_id: str) -> Optional[Dict[str, Any]]: ...
    def list_deployment_plans(self, *args: Any, **kwargs: Any) -> Sequence[Dict[str, Any]]: ...
    def get_deployment_plan(self, plan_id: str) -> Optional[Dict[str, Any]]: ...
    def get_approval_decision(self, decision_id: Optional[str]) -> Optional[Dict[str, Any]]: ...
    def get_review_summary(self, plan_id: str) -> Optional[Dict[str, Any]]: ...
    def get_allowed_actions(self, plan_id: str) -> Optional[Dict[str, Any]]: ...
    def get_capital_pool(self, pool_id: Optional[str]) -> Optional[Dict[str, Any]]: ...
    def get_bindings_for_pool(self, pool_id: Optional[str]) -> Sequence[Dict[str, Any]]: ...
    def get_runtime_binding(self, runtime_binding_id: Optional[str]) -> Optional[Dict[str, Any]]: ...
    def list_runtime_bindings(self) -> Sequence[Dict[str, Any]]: ...
    def get_rollbacks(self, runtime_id: Optional[str]) -> Sequence[Dict[str, Any]]: ...
    def get_latest_run(self, plan_id: str) -> Optional[Dict[str, Any]]: ...
    def get_deployment_diff(self, plan_id: str) -> Optional[Dict[str, Any]]: ...
    def dataset_source(self, dataset: str) -> str: ...
    def get_paper_runtime_monitoring_session(self, *args: Any, **kwargs: Any) -> Optional[Dict[str, Any]]: ...
    def get_telemetry_summary(self, runtime_id: Optional[str]) -> Optional[Dict[str, Any]]: ...


@runtime_checkable
class DeploymentCommands(Protocol):
    """Command interface for deployment mutations."""

    def create_deployment_plan(self, **kwargs: Any) -> Dict[str, Any]: ...


__all__ = ["DeploymentQueries", "DeploymentCommands"]
