"""services/research/imitation contracts and dataset tooling."""

from .dataset_builder import (
    DatasetBuildRequest,
    DatasetBuildResult,
    DatasetBuilderError,
    ImitationDatasetBuilder,
    ImitationDatasetBuilderConfig,
    RawTrajectorySession,
    TrajectoryStep,
    build_dataset,
)
from .preference_models import (
    CorrectionOperation,
    CorrectionOperationType,
    CorrectionTrace,
    GovernedTrainingTarget,
    PreferenceAction,
    PreferenceExample,
    PreferenceValidationError,
    validate_correction_trace_payload,
    validate_preference_example_against_correction_trace,
    validate_preference_example_payload,
)
from .trajectory_models import (
    StorageBackend,
    TraderActorRole,
    TraderDecision,
    TraderTrajectory,
    TraderTrajectoryStep,
    TraderTrajectoryValidationError,
    TrajectoryGovernance,
    TrajectoryLineage,
    TrajectoryStorageRef,
    load_trader_trajectory_schema,
    validate_trader_trajectory_payload,
)

__all__ = [
    "CorrectionOperation",
    "CorrectionOperationType",
    "CorrectionTrace",
    "DatasetBuildRequest",
    "DatasetBuildResult",
    "DatasetBuilderError",
    "GovernedTrainingTarget",
    "ImitationDatasetBuilder",
    "ImitationDatasetBuilderConfig",
    "PreferenceAction",
    "PreferenceExample",
    "PreferenceValidationError",
    "RawTrajectorySession",
    "StorageBackend",
    "TraderActorRole",
    "TraderDecision",
    "TraderTrajectory",
    "TraderTrajectoryStep",
    "TraderTrajectoryValidationError",
    "TrajectoryGovernance",
    "TrajectoryLineage",
    "TrajectoryStorageRef",
    "TrajectoryStep",
    "build_dataset",
    "load_trader_trajectory_schema",
    "validate_correction_trace_payload",
    "validate_preference_example_against_correction_trace",
    "validate_preference_example_payload",
    "validate_trader_trajectory_payload",
]
